export const GetAllBankInfo = '[Bank-Info] Get All Bank Info'
export const CreateBankInfo = '[Bank-Info] Create Bank Info'
export const UpdateBankInfo = '[Bank-Info] Update Bank Info'
export const RemoveBankInfo = '[Bank-Info] Remove Bank Info'
export const PushToFetchingList = '[Bank-Info] Push To Fetching List'
export const RemoveFromFetchingList = '[Bank-Info] Remove From Fetching List'