export const GetManualById = '[Manuals] Get Manual By ID'
export const CreateManual = '[Manuals] Create Manual'
export const UpdateManual = '[Manuals] Update Manual'
export const RemoveManual = '[Manuals] Remove Manual'
export const RecoveryManual = '[Manuals] Recovery Manual'
export const PushToFetchingList = '[Manuals] Push To Fetching List'
export const RemoveFromFetchingList = '[Manuals] Remove From Fetching List'